Repository GSM-MSG/Took-Android, pull requests merged in 2022-09, with the labels that each got.

#5 📄 :: change Background
  .idea/misc.xml
  buildSrc/build/classes/kotlin/main/Dependency$Compose.class
  buildSrc/build/classes/kotlin/main/Dependency$ComposeTest.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
  buildSrc/src/main/java/Version.kt
  data/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/androidTest/java/com/msg/presentation/ExampleInstrumentedTest.kt
  presentation/src/main/java/com/msg/presentation/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Background.kt
  presentation/src/main/res/drawable/background.png
Labels: documentation

#6 🔀 :: (#4) 시작 페이지 퍼블리싱
  .idea/misc.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/start/StartActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Background.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Button.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/TookBackground.kt
  presentation/src/main/res/drawable/ic_bg_blur.xml
Labels: enhancement

#9 🔀 :: (#3)명함 등록 페이지 UI
  .idea/deploymentTargetDropDown.xml
  buildSrc/build/classes/kotlin/main/Dependency$AndroidTest.class
  buildSrc/build/classes/kotlin/main/Dependency$BottomNav.class
  buildSrc/build/classes/kotlin/main/Dependency$Compose.class
  buildSrc/build/classes/kotlin/main/Dependency$ComposeTest.class
  buildSrc/build/classes/kotlin/main/Dependency$Coroutine.class
  buildSrc/build/classes/kotlin/main/Dependency$Google.class
  buildSrc/build/classes/kotlin/main/Dependency$ImageLoad.class
  buildSrc/build/classes/kotlin/main/Dependency$Libraries.class
  buildSrc/build/classes/kotlin/main/Dependency$Lottie.class
  buildSrc/build/classes/kotlin/main/Dependency$Rx.class
  buildSrc/build/classes/kotlin/main/Dependency$UnitTest.class
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/src/main/java/Dependency.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/RegistrationActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Button.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Text.kt
  presentation/src/main/res/font/sfpro.ttf
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: enhancement

#11 🔀 :: (#10)명함 원본 업로드
  .idea/deploymentTargetDropDown.xml
  .idea/vcs.xml
  buildSrc/build/classes/kotlin/main/Dependency$AndroidTest.class
  buildSrc/build/classes/kotlin/main/Dependency$BottomNav.class
  buildSrc/build/classes/kotlin/main/Dependency$Compose.class
  buildSrc/build/classes/kotlin/main/Dependency$ComposeTest.class
  buildSrc/build/classes/kotlin/main/Dependency$Coroutine.class
  buildSrc/build/classes/kotlin/main/Dependency$Google.class
  buildSrc/build/classes/kotlin/main/Dependency$ImageLoad.class
  buildSrc/build/classes/kotlin/main/Dependency$Libraries.class
  buildSrc/build/classes/kotlin/main/Dependency$Lottie.class
  buildSrc/build/classes/kotlin/main/Dependency$Rx.class
  buildSrc/build/classes/kotlin/main/Dependency$UnitTest.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/ui/registration/RegistrationActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Button.kt
Labels: enhancement

#13 🔀 :: (#7) login page
  .gitignore
  .idea/gradle.xml
  buildSrc/build/classes/kotlin/main/Dependency$Compose.class
  buildSrc/build/classes/kotlin/main/Versions.class
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-attributes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/constants.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/proto.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/counters.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/lookups.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/source-roots/buildSrc/source-roots.txt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/registration/RegistrationActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/start/StartActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/start/StartScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/AppBar.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Background.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Button.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/Text.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/TextField.kt
  presentation/src/main/res/drawable/ic_cancel.xml
  presentation/src/main/res/drawable/ic_unvisible.xml
  presentation/src/main/res/drawable/ic_visible.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#15 🔀 :: (#12)uri 전송
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/msg/app/di/DataSourceModule.kt
  app/src/main/java/com/msg/app/di/NetworkModule.kt
  app/src/main/java/com/msg/app/di/RepositoryModule.kt
  app/src/main/java/com/msg/app/di/UseCaseModule.kt
  app/src/main/java/com/msg/app/utils/.gitignore
  app/src/main/java/com/msg/app/utils/BASE_URL.kt
  build.gradle
  data/build.gradle.kts
  data/src/main/java/com/msg/data/local/.gitinit
  data/src/main/java/com/msg/data/remote/datasource/datasource/ImageDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/datasourceImpl/ImageDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/.gitinit
  data/src/main/java/com/msg/data/remote/network/ImageAPI.kt
  data/src/main/java/com/msg/data/repository/ImageRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/msg/domain/.gitinit
  domain/src/main/java/com/msg/domain/repository/ImageRepository.kt
  domain/src/main/java/com/msg/domain/usecase/image/ImageUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/app/TookApplication.kt
  presentation/src/main/java/com/msg/presentation/ui/registration/RegistrationActivity.kt
Labels: enhancement

#19 🔀 :: (#17) change password
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/ui/change_password/ChangePasswordScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/change_password/ConfirmEmailScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/start/StartActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/AppBar.kt
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#21 🔀 :: (#18) 명함 보관함 퍼블리싱
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/card_sotrage/CardStorageHorizentalScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/card_sotrage/CardStorageScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/card_sotrage/CardStorageVerticalScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/home/HomeActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/AppBar.kt
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#25 🔀 :: (#20) registration logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/app/di/DataSourceModule.kt
  app/src/main/java/com/msg/app/di/NetworkModule.kt
  app/src/main/java/com/msg/app/di/RepositoryModule.kt
  app/src/main/java/com/msg/app/di/UseCaseModule.kt
  data/src/main/java/com/msg/data/remote/datasource/datasource/AuthDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/datasource/EmailDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/datasourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/datasource/datasourceImpl/EmailDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/.gitinit
  data/src/main/java/com/msg/data/remote/dto/request/InfoRequest.kt
  data/src/main/java/com/msg/data/remote/network/AuthAPI.kt
  data/src/main/java/com/msg/data/remote/network/EmailAPI.kt
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/msg/data/repository/EmailRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/param/InfoParam.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/repository/EmailRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/SignUpUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/SendEmailUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/VerifyCodeUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/ui/confirm/ConfirmScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/signup/SignUpScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/start/StartActivity.kt
  presentation/src/main/java/com/msg/presentation/utils/SingleLiveEvent.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/signup/SignUpViewModel.kt
Labels: enhancement

#27 🔀 :: nfc read and write
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Version.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/ui/main/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/nfc/NFCActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/nfc/NFCScreen.kt
  presentation/src/main/java/com/msg/presentation/ui/registration/RegistrationActivity.kt
  presentation/src/main/java/com/msg/presentation/ui/theme/TookBackground.kt
  presentation/src/main/res/raw/nfc_effect.json
  presentation/src/main/res/values/strings.xml
Labels: bug, enhancement
